spring:
  application:
    name: hx-client
  servlet:
    multipart:
      max-file-size:
              200MB
    max-request-size:
              215MB

grpc:
  client:
    hx-server: # 自定义服务名
      address: 'static://127.0.0.1:9000' # 调用 gRPC 的地址
      negotiation-type: plaintext # 明文传输



